{
    'name': 'MRP Empaquetado Final - Armado de Tarimas',
    'version': '19.0.1.0.8',
    'summary': 'Empaquetado post-manufactura: cajas, tarimas, etiquetas ZPL y packing list PDF',
    'category': 'Manufacturing',
    'author': 'JKK Pack - Custom',
    'depends': ['mrp', 'sale', 'stock'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/mrp_workcenter_views.xml',
        'views/mrp_production_views.xml',
        'views/mrp_pallet_views.xml',
        'views/mrp_box_views.xml',
        'wizards/packing_wizards_views.xml',
        'reports/packing_list_report.xml',
        'reports/packing_list_template.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': False,
}
