{
    "name": "MRP Empaquetado Final - Armado de Tarimas",
    "version": "19.0.1.9.3",
    "summary": "Empaquetado post-manufactura: cajas/bobinas, tarimas, ZPL y packing list",
    "category": "Manufacturing",
    "author": "Oscar Morocho <oscar.morocho@gateway-resources.com>",
    "depends": ["mrp", "sale", "purchase", "stock", "hr", "mail", "mrp_multi_lot_distribution"],
    "data": [
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/mrp_workcenter_views.xml",
        "views/mrp_production_views.xml",
        "views/mrp_production_jkk_views.xml",
        "views/purchase_order_views.xml",
        "views/stock_move_line_views.xml",
        "views/mrp_pallet_views.xml",
        "views/mrp_box_views.xml",
        "wizards/packing_wizards_views.xml",
        "wizards/label_preview_wizard_views.xml",
        "wizards/stock_label_preview_wizard_views.xml",
        "reports/report_mrp_components.xml",
        "reports/report_mrporder_inherit.xml",
        "reports/purchase_order_report.xml",
        "reports/zebra_receipt_label_zpl.xml",
        "reports/packing_list_report.xml",
        "reports/packing_list_template.xml",
        "reports/box_labels_zpl.xml"
    ],
    "assets": {
        "web.assets_backend": [
            "mrp_packing_final/static/src/scss/zpl_preview.scss",
        ],
    },
    "license": "OPL-1",
    "installable": True,
    "application": False,
}
